data_path: ../data/raw/call_graph.csv
num_chain: 20
num_step: 5
interval_time: 100
observed_time: 100
chain_types:
  - uniform
  - gaussian
  - constant
chain_meta_distribution_params:
  - [2, 4, 6, 8]
  - [2, 8, 0.05, 0.1]
  - [8., 12.]
chain_type_ratio: [0.2, 0.7, 0.1]
edge_types:
  - uniform
  - gaussian
  - constant
edge_meta_distribution_params:
  - [2, 4, 6, 8]
  - [2, 8, 0.05, 0.1]
  - [8., 12.]
edge_type_ratio: [0.2, 0.7, 0.1]
start_steps:
  0: 4
  1: 4
  2: 4
  3: 4
  4: 4
noise_ratio: 0.5
min_chain_len: 10
max_chain_len: 100
min_execute_time: 3.
max_execute_time: 10.
distribution_params_corrected: True
execute_edge_chain_ratio: 0.5

num_samples: 100
