_target_: src.models.gaug_module.GAUGModule

encoder:
  _target_: src.models.components.gaug.GAug
  dim_feats: 768
  n_hidden: 300
  n_classes: 5

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 1e-5

num_mixture: 5

# scheduler:
#   _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#   _partial_: true
#   mode: min
#   factor: 0.1
#   patience: 10

scheduler: NULL

# compile model for faster training with pytorch 2.0
compile: false
