_target_: src.models.gcn_for_graph.GCN4Graph

feat_dim: 128

gcn_layer:
  _target_: src.models.components.gcn_layer.GCNLayer
  input_dim: ${model.feat_dim}
  hidden_dim: 64
  latent_dim: 32

score_layer:
  _target_: src.models.components.score_layer.ScoreLayer
  input_dim: 64
  hidden_dim: 32

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3
  weight_decay: 1e-5